version: '3.8'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    shm_size: 2gb
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=host.docker.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpt4free.rule=Host(`gpt.mathlog.ru`)"
      - "traefik.http.routers.gpt4free.entrypoints=websecure"
      - "traefik.http.routers.gpt4free.tls=true"
      - "traefik.http.services.gpt4free.loadbalancer.server.port=8080"
    ports:
      - "8080:8080" 
    networks:
      - web

networks:
  web:
    external: true
